---
- hosts: ws
  become: 1
  ignore_errors: yes
  tasks:

    - name: Delete Old Artifacts
      file: 
        path: /opt/qa/spg/*.jar
        state: absent

    - name: Get the PID
      shell: lsof -i :8082
      register: pid_output

    - name: Kill Running App
      shell: kill -9 pid_output.stdout
      when: pid_output.stdout != ''

    - name: Download New Artifact
      get_url: 
        url: http://3.238.221.96:8082/artifactory/ansible/ansible-37.zip
        dest: /opt/qa/spg
        url_username: admin
        url_password: Devops123
        
    - name : Run the app
      shell : nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &